from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from django.views.decorators.http import require_http_methods
from apps.core.models.models__pages import *
from apps.core.models.models__messages import Subscription
from apps.core.functions import SendMessage
import json
import datetime



def robots(request):
    # content = 'any string generated by django'
    # return HttpResponse(content, content_type='text/plain')
    now = datetime.datetime.now()
    html = "<html><body>It is now %s.</body></html>" % now
    return HttpResponse(html, content_type='text/plain')



def PageView(request, slug):
    for field in Page._meta.fields:
        if field.get_internal_type() == 'TextField':
            for meth in field.__dir__():
                try:
                    attr = getattr(field, meth)
                except: pass
                
    
    return render(request, 'core/text_content.html', {
        'page' : Page.objects.get(slug=slug)
    })




def Contacts(request):
    args = {}
    if request.method == 'POST':
        form = ContactsForm(request.POST)
        if form.is_valid():
            form.save()
            msg =  'Сообщение от ' + request.POST.get('name') + '\n'
            msg += 'E-mail: ' + request.POST.get('email') + '\n'
            msg += 'Текст письма: ' + '\n'
            msg += request.POST.get('text')
            SendMessage(str(msg))
        else:
            args['contacts_form'] = form
    else:
        args['contacts_form'] = ContactsForm()
    return render(request, 'core/pages/contacts.html', args)


@require_http_methods(["POST"])
def subscription(request):
    subscribe = Subscription()
    subscribe.email = request.POST['email']
    try: subscribe.save()
    except: pass
    return redirect('/')